baseurl = "/"
languageCode = "en-us"
title = "Homepage"
DefaultContentLanguage = "en"
copyright = "Everything is mine"

[languages]
  [languages.en]
    title = "My blog"
    weight = 1
    [languages.en.params]
      linkedin = "english-link"
  [languages.fr]
    copyright = "Tout est à moi"
    title = "Mon blog"
    weight = 2
    [languages.fr.params]
      linkedin = "lien-francais"
      [languages.fr.params.navigation]
        help = "Aide"

[params]
  [params.navigation]
    help = "Help"
