baseurl = "/"
languageCode = "en-us"
title = "Homepage"
DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "English"
    weight = 1
  [languages.ae]
    title = "AE"
    weight = 2
  [languages.bh]
    title = "BH"
    weight = 2
 
