baseurl = "/"
languageCode = "en-us"
title = "Homepage"
defaultContentLanguage = "en"


[Languages]
[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"

[Languages.fr]
title = "Documentation du thème Hugo Learn"
weight = 2
languageName = "Français"
