backend:
  name: git-gateway

media_folder: "site/static/img"
public_folder: "img"

publish_mode: editorial_workflow # optional, enables publishing workflow

collections:
  - name: "countries"
    label: "Countries"
    label_singular: "Country"
    folder: "site/content/countries"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "name", name: "name", widget: "string"}
  - name: "Page"
    label: "Blog in AE"
    filter: {field: "country", value: "ae"}
    folder: "site/content/pages/ae"
    create: true
    fields:
      - label: "Post Author"
        name: "author"
        widget: "relation"
        collection: "countries"
        displayFields: ["title", "name"]
        searchFields: ["title", "name"]
        valueField: "title"
      - {label: "Country", name: "country", widget: "select", options: ["ae", "bh"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "bh_pages"
    label: "Blog in BH"
    filter: {field: "country", value: "bh"}
    folder: "site/content/pages/bh"
    create: true
    fields:
      - {label: "Country", name: "country", widget: "select", options: ["ae", "bh"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "ae_links"
    label: "Liens dans AE"
    folder: "site/content/links"
    filter: {field: "country", value: "ae"}
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Country", name: "country", widget: "select", options: ["ae", "bh"]}
      
