backend:
  name: git-gateway

media_folder: "site/static/img"
public_folder: "img"

collections:
  - name: "ae_pages"
    label: "Blog in AE"
    filter: {field: "country", value: "ae"}
    folder: "site/content/pages/ae"
    create: true
    fields:
      - {label: "Country", name: "country", widget: "select", options: ["ae", "bh"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "bh_pages"
    label: "Blog in BH"
    filter: {field: "country", value: "bh"}
    folder: "site/content/pages/bh"
    create: true
    fields:
      - {label: "Country", name: "country", widget: "select", options: ["ae", "bh"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
- label: "Links"
  name: "links"
  files:
    - label: "Links AE"
      name: "links_ae"
      file: "site/content/links_ae.yml"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Url, name: url, widget: string}
    - label: "Links BH"
      name: "links_bh"
      file: "site/content/links_bh.yml"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Url, name: url, widget: string}
